### ISSUE TITLE
error on extractXML

### ISSUE THREAD

**Issue by fdsayre** [christopherBelter/scopusAPI#1]
I receive the following error on extractXML using basically the same example as is given in the readme:

>  Error: 1: XML declaration allowed only at the start of the document
2: XML declaration allowed only at the start of the document
3: XML declaration allowed only at the start of the document
4: Premature end of data in tag search-results line 3
5: Premature end of data in tag search-results line 1
6: Premature end of data in tag search-results line 1

**Comment by christopherBelter** [comment]
Ah, yes. Elsevier unexpectedly changed the XML headers of the returned XML without notifying anyone, causing the parsing to fail. I'll upload a new version shortly that fixes the problem and should be immune to such changes in the future.

**Comment by fdsayre** [comment]
Thanks!

---
Franklin Darrow Sayre
frank.darrow@gmail.com
---
